version: 0.0
os: linux
files:
  # Que archivos se copiaran en la instancia
  # https://docs.aws.amazon.com/codedeploy/latest/userguide/tutorials-on-premises-instance-2-create-sample-revision.html
  - source: ./docker-compose.production.yml
    # Carpeta donde lo vamos a dejar
    destination: /home/ubuntu/docker-compose.yml  # Rename to docker-compose.yml on deployment
  - source: ./.env
    destination: /home/ubuntu/.env
  - source: scripts
    destination: /home/ubuntu/scripts

# Ciclo de vida del deployment 
# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 120
      runas: ubuntu
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: scripts/validate-service.sh
      timeout: 60
      runas: ubuntu